version: "2.3"

services:
    web:
        image: nginx:1.17
        ports:
            - "80:80"
        volumes:
            - ../:/var/www
            - ./sites:/etc/nginx/conf.d
        networks:
            app:
                aliases:
                    - php53.vm
                    - php56.vm
                    - php71.vm


    php53:
        build:
            context: ./php/php53
        volumes:
            - ../:/var/www
            - ./php/php53/php.conf:/usr/local/etc/php-fpm.conf
        networks:
            - app

    php56:
        build:
            context: ./php/php56
        volumes:
            - ../:/var/www
            - ./php/php56/php.conf:/usr/local/etc/php-fpm.d/php.conf
        networks:
            - app

    php71:
        build:
            context: ./php/php71
        volumes:
            - ../:/var/www
            - ./php/php71/php.conf:/usr/local/etc/php-fpm.d/php.conf
        networks:
            - app


    database01:
        image: mariadb:10
        ports:
            - 3306:3306
        hostname: mariadb01
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app


networks:
    app:
